from: mpecarina/api-gateway:latest
workDir: /api-gateway
services:
  - postgres:
      from: postgres:latest
      env:
        - POSTGRES_USER=${DB_USER:-postgres}
        - POSTGRES_DB=${DB_NAME:-postgres}
        - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      expose:
        - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
env:
  - APP_VERSION=${APP_VERSION:-0.0.0}
  - STATIC_DIR=./static
  - STATIC_PATH=false
  # - NOT_FOUND_FILE=index.html
  - NODE_ENV=test
  - APP_NAME=api-gateway
  - APP_PORT_0=3000
  - APP_PORT_1=3001
  # - TOKEN_PATH=/api-gateway/token.json
  # - REFRESH_TOKEN=temporary-refresh-token
  # - IMPERSONATE_USER_EMAIL=ldapbind@example.com
  - STORE_TOKEN=false
  - SECRET_KEY=api-gw-local-cookie
  # - SERVICE_ACCOUNT_JSON=/api-gateway/auth-devops.json
  # - GATEWAY_KEY_PATH=/api-gateway/auth-gateway-credentials.json
  - DB_PORT=5432
  - DB_NAME=postgres
  - DB_USER=postgres
  - DB_PASSWORD=password
  - PGPASSWORD=password
expose:
  - ${APP_PORT_0:-3000}:${APP_PORT_0:-3000}
  - ${APP_PORT_1:-3001}:${APP_PORT_1:-3001}
# before: |
#   sleep 3
#   export DB_HOST=${POSTGRES_PORT_5432_TCP_ADDR}
#   yarn --cwd /${APP_NAME:-api-gateway} mock
tasks:
  env: env | sort
  build: yarn
  shell: /bin/sh
  mock: yarn --cwd /${APP_NAME:-api-gateway} mock
  test: yarn --cwd /${APP_NAME:-api-gateway} test
  dev: yarn --cwd /${APP_NAME:-api-gateway} && yarn --cwd /${APP_NAME:-api-gateway} dev
